spring:
    datasource:
#      url: jdbc:h2:file:./happy-db
      url: jdbc:h2:mem:happy-db
      username: sa
      password: sa
      driver-class-name: org.h2.Driver
    jpa:
      open-in-view: true
      show-sql: true
      hibernate:
        ddl-auto: create
        show-sql: true
